/**
 * POST /api/referrals/invite
 *
 * Called when a talent fills out the "Refer a Talent" form on a job page.
 * Creates a submission + referral_invite row, then emails the referred person.
 *
 * Supabase table required (run once in the Supabase SQL editor):
 * ─────────────────────────────────────────────────────────────────
 * create table if not exists referral_invites (
 *   id                uuid primary key default gen_random_uuid(),
 *   token             text unique not null default encode(gen_random_bytes(24), 'hex'),
 *   job_id            uuid references jobs(id) on delete set null,
 *   referrer_id       uuid not null,
 *   referred_email    text not null,
 *   referred_name     text,
 *   submission_id     uuid references submissions(id) on delete set null,
 *   referred_user_id  uuid references profiles(id) on delete set null,
 *   status            text not null default 'pending',
 *   commission_paid   numeric(12,2),
 *   created_at        timestamptz default now()
 * );
 * alter table referral_invites enable row level security;
 * create policy "referrer_read" on referral_invites
 *   for select using (auth.uid() = referrer_id);
 * ─────────────────────────────────────────────────────────────────
 */

import { NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@/lib/supabase";
import { sendEmail } from "@/lib/email";
import { notify } from "@/lib/notify";

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { job_id, referrer_id, referred_email, referred_name, bio } = body;

  if (!job_id || !referrer_id || !referred_email) {
    return NextResponse.json(
      { error: "job_id, referrer_id e referred_email são obrigatórios" },
      { status: 400 }
    );
  }

  const supabase = createServerClient({ useServiceRole: true });

  // Fetch the job details for email copy
  const { data: job } = await supabase
    .from("jobs")
    .select("title, agency_id")
    .eq("id", job_id)
    .single();

  // Create a pending submission (mode = "other", talent is not yet registered)
  const { data: submission, error: subErr } = await supabase
    .from("submissions")
    .insert({
      job_id,
      talent_user_id: null,
      talent_name: referred_name ?? null,
      email: referred_email,
      bio: bio ?? null,
      referrer_id,
      status: "pending",
      mode: "other",
    })
    .select("id")
    .single();

  if (subErr) {
    console.error("[POST /api/referrals/invite] submission error:", subErr);
    return NextResponse.json({ error: subErr.message }, { status: 400 });
  }

  // Create the referral_invite row (token auto-generated by DB default)
  const { data: invite, error: inviteErr } = await supabase
    .from("referral_invites")
    .insert({
      job_id,
      referrer_id,
      referred_email,
      referred_name: referred_name ?? null,
      submission_id: submission.id,
      status: "pending",
    })
    .select("id, token")
    .single();

  if (inviteErr) {
    console.error("[POST /api/referrals/invite] invite error:", inviteErr);
    return NextResponse.json({ error: inviteErr.message }, { status: 400 });
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  const signupLink = `${appUrl}/signup?role=talent&ref=${invite.token}`;
  const jobTitle = job?.title ?? "uma vaga";

  // Send invite email to the referred person
  await sendEmail({
    to: referred_email,
    subject: `Você foi indicado para "${jobTitle}" na Brisa Digital`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;color:#1a1a1a">
        <h2 style="font-size:20px;font-weight:700;margin-bottom:8px">Você recebeu uma indicação!</h2>
        <p style="font-size:15px;color:#555;line-height:1.6;margin-bottom:24px">
          Alguém acredita que você é o talento certo para
          <strong>${jobTitle}</strong>.
          Crie sua conta gratuita na Brisa Digital e candidate-se com um clique.
        </p>
        <a href="${signupLink}"
           style="display:inline-block;background:#18181b;color:#fff;font-size:14px;font-weight:600;
                  padding:12px 28px;border-radius:12px;text-decoration:none">
          Criar conta e candidatar-se
        </a>
        <p style="font-size:12px;color:#aaa;margin-top:32px">
          Se você não esperava este e-mail, pode ignorá-lo com segurança.
        </p>
      </div>
    `,
  });

  // Notify the agency that a new referral submission arrived
  if (job?.agency_id) {
    await notify(
      job.agency_id,
      "job_application",
      `${referred_name ?? referred_email} foi indicado(a) para "${jobTitle}"`,
      "/agency/submissions"
    );
  }

  return NextResponse.json({ ok: true, invite_id: invite.id }, { status: 201 });
}
